codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        target: 100%
        threshold: 0%
        if_ci_failed: error
    
    patch:
      default:
        target: 100%
        threshold: 0%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "Tests/**/*"
  - "**/*.xcconfig"
  - "**/*.plist"
