disabled_rules:
  - trailing_comma
  - force_cast  # Disabled for numeric conversions in decoder/encoder
  - opening_brace  # Disabled to allow SwiftFormat to handle brace spacing
  - non_optional_string_data_conversion  # Allow optional Data initialization from String

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_first_last
  - unused_optional_binding

included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - coverage_html
  - coverage_report

line_length:
  warning: 120
  error: 150
  ignores_comments: true

type_body_length:
  warning: 800
  error: 1000

file_length:
  warning: 1150
  error: 1500

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - x
    - y
    - z
    - id

type_name:
  min_length:
    warning: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - _DictionaryCoder
    - _DictionaryEncoder
  validates_start_with_lowercase: true

function_body_length:
  warning: 100
  error: 150

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
